version: "3"
services:
  app:
    build:
      context: .
      target: builder
    ports:
      - 1323:1323
    volumes:
      - ./:/app/
    environment:
      APP_DB_HOST: mysql
      APP_DB_USER: root
      APP_DB_PASSWORD: ""
    entrypoint:
      ["/app/scripts/wait-for-it.sh", "mysql:3306", "-t", "60", "--", "air"]
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./configs/sql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
