name: Test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: docker-compose build
      - name: Test
        run: |
          docker-compose up -d
          docker-compose exec -T app /app/scripts/wait-for-it.sh localhost:1323 -t 30 -- go test -v -covermode=atomic -coverprofile=coverage.out ./...
          docker cp `docker-compose ps -q app`:/app/coverage.out ./
      - name: Convert gcov to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
